### PR TITLE
Release 131

### PR DESCRIPTION
**Pull request by tlacloc**

### CODE REVIEW

**Review by sebastianmontero — COMMENTED** [review]
It looks good to me, only one question did you consider having a catalog of banks? And the projects referencing those. Instead of defining new banks for each project?

**Comment by didiermis** [comment]
@sebastianmontero There isn't such a catalog of banks at this moment. Users type a back name & address for each entry.

**Comment by sebastianmontero** [comment]
Yes, I was just wondering if at some point you considered  having a bank catalog, and if so why you decided against it?

**Comment by tlacloc** [comment]
> Yes, I was just wondering if at some point you considered having a bank catalog, and if so why you decided against it?

@sebastianmontero Yes! We did at some point as we can reuse this information for other projects (and have information of all banks that participate), but we decided to not create a new storage map for banks as it was going to be more calls for the front end team. Also the plan is latter migrate that to a storage map when we implement a cache layer this information could be query easily

**Pull request merged**
